title: "Bite-Analytics"
description: "Bite-sized insights on Business Intelligence and Artificial Intelligence"
url: "https://bite-analytics.com"
baseurl: "" # leave blank for root

logo: "/assets/images/avatar.png"
favicon: "/assets/images/favicon.ico"

author:
  name: "Bite-Analytics"
  avatar: "/assets/images/avatar.png"
  bio: "Bite-sized insights into BI & AI"
  location: "UK"

sass:
  style: compressed

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"  # or "air", "contrast", "default"
color_scheme_toggle: true

markdown: kramdown
highlighter: rouge

permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      custom_css: assets/css/custom.css
  - scope:
      path: ""
      type: "pages"
    values:
      custom_css: assets/css/custom.css

# Social media links (update as you grow)
social:
  type: "Person"
  name: "Bite-Analytics"
  links:
    - "https://www.youtube.com/@biteanalytics"
    - "https://github.com/bite-analytics"

# Build settings
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor"]
